'use client';
import React,{useEffect,useMemo,useState}from'react';
import{Home,Package,ShoppingBag,Wallet,Settings,Plus,Search,ChevronRight,CalendarDays,ClipboardList,UserRound,Coins,Box,Truck,Filter,Hash,Phone,MapPin,X,Save,Trash2,Printer,ArrowLeft,CheckCircle2,Clock3,MoreHorizontal}from'lucide-react';
const seedOrders=[
{id:'MF-250520-001',date:'2026-05-20',customer:'林小姐',phone:'0912-345-678',address:'台中市西屯區市政路 100 號',shipping:'7-11 店到店',pay:'待付款',shipStatus:'待出貨',items:[{name:'奶油小花洋裝',variant:'100 / 粉色',qty:1,price:1280}],fee:60,discount:0,note:'請幫我分開包裝'},
{id:'MF-250520-002',date:'2026-05-20',customer:'王小姐',phone:'0988-123-456',address:'新北市板橋區文化路 50 號',shipping:'黑貓宅急便',pay:'已付款',shipStatus:'已包貨',items:[{name:'韓系棉麻外套',variant:'M / 杏色',qty:1,price:2450}],fee:100,discount:100,note:'上班時段配送'},
{id:'MF-250519-018',date:'2026-05-19',customer:'陳小姐',phone:'0922-888-777',address:'台北市信義區忠孝東路 123 號',shipping:'全家店到店',pay:'已付款',shipStatus:'已完成',items:[{name:'日系條紋上衣',variant:'90 / 米白',qty:1,price:890}],fee:60,discount:60,note:''},
{id:'MF-250519-019',date:'2026-05-19',customer:'張小姐',phone:'0933-555-666',address:'桃園市中壢區中正路 20 號',shipping:'宅配',pay:'待付款',shipStatus:'待出貨',items:[{name:'柔霧質感長袖上衣',variant:'L / 粉色',qty:2,price:780}],fee:80,discount:0,note:'預購商品先保留'}
];
const seedProducts=[{id:'P001',name:'奶油小花洋裝',sku:'DR-2505-001',price:1280,stock:12},{id:'P002',name:'韓系棉麻外套',sku:'JK-2505-002',price:2450,stock:5}];
function money(n){return 'NT$'+Number(n||0).toLocaleString()}
function sum(o){return (o.items||[]).reduce((s,i)=>s+(+i.qty||0)*(+i.price||0),0)+(+o.fee||0)-(+o.discount||0)}
function useLocal(key,seed){const[v,setV]=useState(seed);useEffect(()=>{try{let s=localStorage.getItem(key);if(s)setV(JSON.parse(s));else localStorage.setItem(key,JSON.stringify(seed))}catch{}},[]);useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(v))}catch{}},[v]);return[v,setV]}
const nav=[['dashboard','總覽',Home],['orders','訂單',Package],['products','商品',ShoppingBag],['finance','財務',Wallet],['settings','設定',Settings]];
const statuses=['全部','待出貨','已包貨','已出貨','已完成','待付款','已付款'];
const dates=[['all','全部日期'],['today','今天'],['week','本週'],['month','本月']];
function inRange(date,range){if(range==='all')return true;const d=new Date(date+'T00:00:00'),now=new Date();const today=new Date(now.getFullYear(),now.getMonth(),now.getDate());if(range==='today')return d.toDateString()===today.toDateString();if(range==='month')return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth();if(range==='week'){const day=today.getDay()||7;const monday=new Date(today);monday.setDate(today.getDate()-day+1);return d>=monday&&d<=now}return true}
export default function App(){const[page,setPage]=useState('orders');const[orders,setOrders]=useLocal('mf_orders_v3',seedOrders);const[products,setProducts]=useLocal('mf_products_v3',seedProducts);const[modal,setModal]=useState(null);const[selected,setSelected]=useState(null);function go(p,id){setPage(p);setSelected(id||null);window.scrollTo({top:0,behavior:'smooth'})}return <div className="shell"><header className="topHeader"><button className="brand" onClick={()=>go('dashboard')}><span className="logo">M</span><span><b>MoriFlow</b><small>SELLER OS</small></span></button><button className="login">登入</button></header><main className="content">{page==='dashboard'&&<Dashboard orders={orders} go={go}/>} {page==='orders'&&<Orders orders={orders} setOrders={setOrders} go={go} openNew={()=>setModal('order')}/>} {page==='orderDetail'&&<OrderDetail order={orders.find(x=>x.id===selected)} setOrders={setOrders} back={()=>go('orders')}/>} {page==='products'&&<Products products={products}/>} {page==='finance'&&<Finance orders={orders}/>} {page==='settings'&&<SettingsPage/>}</main><nav className="bottomNav">{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}><Icon size={24}/><span>{label}</span></button>)}</nav>{modal==='order'&&<OrderModal onClose={()=>setModal(null)} onSave={o=>{setOrders([o,...orders]);setModal(null);go('orders')}}/>}</div>}
function PageTitle({en,zh}){return <section className="titleBlock"><p>{en}</p><h1>{zh}</h1></section>}
function Dashboard({orders,go}){return <><PageTitle en="Dashboard" zh="總覽"/><section className="quickStats"><button onClick={()=>go('orders')}><ClipboardList/><span>訂單</span><b>{orders.length}</b></button><button onClick={()=>go('orders')}><Box/><span>待出貨</span><b>{orders.filter(o=>o.shipStatus==='待出貨').length}</b></button><button onClick={()=>go('finance')}><Coins/><span>營收</span><b>{money(orders.reduce((s,o)=>s+sum(o),0))}</b></button></section></>}
function Orders({orders,setOrders,go,openNew}){const[query,setQuery]=useState('');const[status,setStatus]=useState('全部');const[date,setDate]=useState('all');const filtered=useMemo(()=>orders.filter(o=>{const q=query.trim().toLowerCase();const text=[o.id,o.customer,o.phone,o.shipping,o.pay,o.shipStatus].join(' ').toLowerCase();return(!q||text.includes(q))&&(status==='全部'||o.shipStatus===status||o.pay===status)&&inRange(o.date,date)}),[orders,query,status,date]);const total=filtered.reduce((s,o)=>s+sum(o),0);return <><PageTitle en="Orders" zh="訂單管理"/><button className="bigAdd" onClick={openNew}><Plus size={22}/>新增訂單</button><section className="filterCard"><div className="filterHead"><span><Filter size={18}/></span><div><b>即時篩選</b><small>不用再按篩選，輸入或點選後立即更新</small></div></div><label className="searchBox"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋訂單 / 客戶 / 電話 / 配送方式"/></label><div className="chips">{statuses.map(x=><button key={x} className={status===x?'on':''} onClick={()=>setStatus(x)}>{x}<em>{x==='全部'?orders.length:orders.filter(o=>o.shipStatus===x||o.pay===x).length}</em></button>)}</div><div className="dateChips">{dates.map(([id,label])=><button key={id} className={date===id?'on':''} onClick={()=>setDate(id)}><CalendarDays size={16}/>{label}</button>)}</div></section><section className="summaryStrip"><button><ClipboardList size={18}/><span>目前顯示</span><b>{filtered.length} 筆</b></button><button><Box size={18}/><span>待處理</span><b>{filtered.filter(o=>o.shipStatus==='待出貨'||o.shipStatus==='已包貨').length} 筆</b></button><button><Coins size={18}/><span>篩選金額</span><b>{money(total)}</b></button></section><section className="orderList">{filtered.length?filtered.map(o=><button key={o.id} className="orderCard" onClick={()=>go('orderDetail',o.id)}><div className="cardHeader"><span className="headIcon"><Hash size={16}/></span><b>{o.id}</b><StatusBadge text={o.shipStatus}/></div><div className="cardGrid"><span><UserRound size={16}/>{o.customer}</span><span><Coins size={16}/>{money(sum(o))}</span><span><CalendarDays size={16}/>{o.date}</span><span><Truck size={16}/>{o.shipping}</span></div><div className="cardFooter"><small>{o.pay}</small><ChevronRight size={22}/></div></button>):<div className="empty">找不到符合條件的訂單</div>}</section></>}
function StatusBadge({text}){let cls=text==='已完成'?'done':text==='已付款'?'paid':text==='待付款'?'unpaid':text==='已包貨'?'packed':'pending';return <span className={'badge '+cls}>{text}</span>}
function OrderDetail({order,setOrders,back}){const[o,setO]=useState(order);if(!order)return <div>找不到訂單</div>;function save(){setOrders(prev=>prev.map(x=>x.id===o.id?o:x));alert('已儲存')}function print(){window.print()}return <><button className="back" onClick={back}><ArrowLeft size={18}/>返回訂單</button><PageTitle en="Order Detail" zh="訂單詳細"/><section className="detailCard"><div className="detailHead"><b><Hash size={18}/>{o.id}</b><StatusBadge text={o.shipStatus}/></div><div className="form"><label>客戶<input value={o.customer} onChange={e=>setO({...o,customer:e.target.value})}/></label><label>電話<input value={o.phone} onChange={e=>setO({...o,phone:e.target.value})}/></label><label>地址<input value={o.address} onChange={e=>setO({...o,address:e.target.value})}/></label><label>配送<select value={o.shipping} onChange={e=>setO({...o,shipping:e.target.value})}><option>7-11 店到店</option><option>全家店到店</option><option>黑貓宅急便</option><option>宅配</option></select></label><label>出貨狀態<select value={o.shipStatus} onChange={e=>setO({...o,shipStatus:e.target.value})}><option>待出貨</option><option>已包貨</option><option>已出貨</option><option>已完成</option></select></label><label>付款狀態<select value={o.pay} onChange={e=>setO({...o,pay:e.target.value})}><option>待付款</option><option>已付款</option></select></label></div><h3>商品明細</h3>{o.items.map((it,i)=><div className="item" key={i}><input value={it.name} onChange={e=>{let a=[...o.items];a[i].name=e.target.value;setO({...o,items:a})}}/><input value={it.variant} onChange={e=>{let a=[...o.items];a[i].variant=e.target.value;setO({...o,items:a})}}/><input type="number" value={it.qty} onChange={e=>{let a=[...o.items];a[i].qty=+e.target.value;setO({...o,items:a})}}/><input type="number" value={it.price} onChange={e=>{let a=[...o.items];a[i].price=+e.target.value;setO({...o,items:a})}}/></div>)}<div className="totalBox"><span>商品小計 <b>{money(o.items.reduce((s,i)=>s+i.qty*i.price,0))}</b></span><span>運費 <input type="number" value={o.fee} onChange={e=>setO({...o,fee:+e.target.value})}/></span><span>折扣 <input type="number" value={o.discount} onChange={e=>setO({...o,discount:+e.target.value})}/></span><strong>訂單總金額 {money(sum(o))}</strong></div><div className="actions"><button className="primary" onClick={save}><Save size={18}/>儲存</button><button onClick={print}><Printer size={18}/>列印</button><button className="danger" onClick={()=>{if(confirm('確定刪除？')){setOrders(prev=>prev.filter(x=>x.id!==o.id));back()}}}><Trash2 size={18}/>刪除</button></div></section></>}
function Products({products}){return <><PageTitle en="Products" zh="商品管理"/><section className="orderList">{products.map(p=><div className="orderCard" key={p.id}><div className="cardHeader"><b>{p.name}</b><StatusBadge text={p.stock<=5?'低庫存':'上架'}/></div><div className="cardGrid"><span><Hash size={16}/>{p.sku}</span><span><Coins size={16}/>{money(p.price)}</span><span><Box size={16}/>庫存 {p.stock}</span></div></div>)}</section></>}
function Finance({orders}){return <><PageTitle en="Finance" zh="財務"/><section className="quickStats"><button><Coins/><span>總營收</span><b>{money(orders.reduce((s,o)=>s+sum(o),0))}</b></button><button><Clock3/><span>待付款</span><b>{orders.filter(o=>o.pay==='待付款').length} 筆</b></button></section></>}
function SettingsPage(){return <><PageTitle en="Settings" zh="設定"/><section className="detailCard"><p>這一版已改為：即時篩選、整張訂單卡片可點、日期範圍整個按鈕可點、卡片表頭新增圖示、字體重新整理。</p></section></>}
function OrderModal({onClose,onSave}){const[o,setO]=useState({customer:'',phone:'',address:'',shipping:'7-11 店到店',pay:'待付款',shipStatus:'待出貨',items:[{name:'',variant:'',qty:1,price:0}],fee:60,discount:0,note:''});return <div className="overlay"><div className="modal"><div className="modalHead"><h2>新增訂單</h2><button onClick={onClose}><X/></button></div><div className="form"><label>客戶<input value={o.customer} onChange={e=>setO({...o,customer:e.target.value})}/></label><label>電話<input value={o.phone} onChange={e=>setO({...o,phone:e.target.value})}/></label><label>地址<input value={o.address} onChange={e=>setO({...o,address:e.target.value})}/></label><label>配送方式<select value={o.shipping} onChange={e=>setO({...o,shipping:e.target.value})}><option>7-11 店到店</option><option>全家店到店</option><option>黑貓宅急便</option><option>宅配</option></select></label></div><h3>商品明細</h3>{o.items.map((it,i)=><div className="item" key={i}><input placeholder="商品名稱" value={it.name} onChange={e=>{let a=[...o.items];a[i].name=e.target.value;setO({...o,items:a})}}/><input placeholder="規格" value={it.variant} onChange={e=>{let a=[...o.items];a[i].variant=e.target.value;setO({...o,items:a})}}/><input type="number" value={it.qty} onChange={e=>{let a=[...o.items];a[i].qty=+e.target.value;setO({...o,items:a})}}/><input type="number" value={it.price} onChange={e=>{let a=[...o.items];a[i].price=+e.target.value;setO({...o,items:a})}}/></div>)}<button className="secondary" onClick={()=>setO({...o,items:[...o.items,{name:'',variant:'',qty:1,price:0}]})}>新增商品列</button><div className="actions"><button className="primary" onClick={()=>onSave({...o,id:'MF-'+new Date().toISOString().slice(2,10).replaceAll('-','')+'-'+String(Date.now()).slice(-3),date:new Date().toISOString().slice(0,10)})}>建立訂單</button></div></div></div>}
